### ISSUE TITLE
Product ID is shows on Create Product

### ISSUE THREAD

**Issue by Ungerfall** [malicuss/Task_SimpleWebApp#3]
![image](https://user-images.githubusercontent.com/8143895/197418171-ad02ba0c-66c6-4827-8e0e-76ddf82c92d5.png)

**Comment by malicuss** [comment]
Hidden now
https://github.com/malicuss/Task_SimpleWebApp/commit/33a8c4ab71d46e8e0c30e0eecbe6412e5efb0f1f
